[package]
name = "butter"
version = "0.1.0"
edition = "2021"
default-run = "butter"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
parser = { path = "../parser/" }
hir = { path = "../hir/" }
type-system = { path = "../type-system/" }
