[package]
name = "hir"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
string_cache = "0.8.7"

[build-dependencies]
string_cache_codegen = "0.5.2"

[package.metadata.cargo-machete]
ignored = ["string_cache"]
